# 512 first
CUDA_VISIBLE_DEVICES=3 python main.py --root_dir ./data/processed/R --target_dir ./data/processed/V --lambda_cycle 10 --num_epochs 30 --save_path ./checkpoints/CycleGAN/Base --generated_image_save_path generated_images/CycleGAN/Base --batch_size 3 --run_name Base


# test code
CUDA_VISIBLE_DEVICES=3 python main.py --root_dir ./data/processed/V --target_dir ./data/processed/R --lambda_cycle 10 --num_epochs 106 --save_path ./checkpoints/CycleGAN/test --generated_image_save_path generated_images/CycleGAN/test --batch_size 3 --run_name test --initialization_epochs 0

# BaseCode
CUDA_VISIBLE_DEVICES=3 python main.py --root_dir ./data/processed/V --target_dir ./data/processed/R --lambda_cycle 10 --num_epochs 101 --save_path ./checkpoints/CycleGAN/Base --generated_image_save_path generated_images/CycleGAN/Base --batch_size 3 --run_name Base --n_res 4
# U_NetCode
CUDA_VISIBLE_DEVICES=2 python main.py --root_dir ./data/processed/V --target_dir ./data/processed/R --lambda_cycle 10 --num_epochs 101 --save_path ./checkpoints/CycleGAN/U_Net --generated_image_save_path generated_images/CycleGAN/U_Net --batch_size 2 --run_name U_Net --model U_Net
# Att_UNet
CUDA_VISIBLE_DEVICES=1 python main.py --root_dir ./data/processed/V --target_dir ./data/processed/R --lambda_cycle 10 --num_epochs 101 --save_path ./checkpoints/CycleGAN/AttU_Net --generated_image_save_path generated_images/CycleGAN/AttU_Net --batch_size 2 --run_name AttU_Net --model AttU_Net

# metric fid
- at dental directory
python metric/fid.py --path ./generated_images/LPIPS_Histogram_matching ./data/processed/V --img_size 256 --batch_size 64


RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]
